import { useEffect, useState } from 'react'
import { Line } from 'react-chartjs-2'
import { Chart as ChartJS, LineElement, PointElement, LinearScale, CategoryScale, Tooltip, Filler, Legend } from 'chart.js'
import { useAuth } from '../context/authContextValue'
import { apiFetch } from '../services/api'

ChartJS.register(LineElement, PointElement, LinearScale, CategoryScale, Tooltip, Filler, Legend)

function downloadCSV(records) {
  const headers = ['Date', 'Action', 'Confidence', 'Mode', 'Savings (R)', 'Solar (kWh)', 'Load Shedding Stage', 'SOC (%)', 'Tariff Rate', 'Peak Rate', 'Reasoning']
  const rows = records.map(r => [
    new Date(r.createdAt).toLocaleString('en-ZA'),
    r.action,
    (r.confidence * 100).toFixed(1) + '%',
    r.operatingMode,
    r.estimatedSavingsRand.toFixed(2),
    r.solarForecastKwh.toFixed(2),
    r.loadSheddingStage,
    r.currentSoc.toFixed(1),
    r.currentTariffRate.toFixed(4),
    r.peakTariffRate.toFixed(4),
    `"${(r.reasoning || '').replace(/"/g, '""')}"`,
  ])
  const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n')
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `optigrid-report-${new Date().toISOString().slice(0, 10)}.csv`
  a.click()
  URL.revokeObjectURL(url)
}

function downloadPDF(records, companyName) {
  const title = `OptiGrid ZA — Prediction Report`
  const date = new Date().toLocaleString('en-ZA')
  const totalSavings = records.reduce((s, r) => s + r.estimatedSavingsRand, 0)
  const avgConfidence = records.length ? records.reduce((s, r) => s + r.confidence, 0) / records.length : 0

  let html = `<html><head><title>${title}</title><style>
    body{font-family:Arial,sans-serif;padding:40px;color:#222}
    h1{color:#F2610C;font-size:22px}h2{font-size:16px;margin-top:24px}
    table{width:100%;border-collapse:collapse;font-size:12px;margin-top:12px}
    th,td{border:1px solid #ddd;padding:6px 8px;text-align:left}
    th{background:#f5f5f5;font-weight:600}
    .summary{display:flex;gap:32px;margin:16px 0}
    .stat{background:#f9f9f9;padding:12px 20px;border-radius:8px}
    .stat-val{font-size:24px;font-weight:700;color:#1E7A6B}
    .stat-label{font-size:11px;color:#666}
    @media print{body{padding:20px}}
  </style></head><body>
  <h1>⚡ ${title}</h1>
  <p style="color:#666;font-size:13px">${companyName ? companyName + ' · ' : ''}Generated ${date}</p>
  <div class="summary">
    <div class="stat"><div class="stat-val">R${totalSavings.toFixed(2)}</div><div class="stat-label">Total savings</div></div>
    <div class="stat"><div class="stat-val">${(avgConfidence * 100).toFixed(0)}%</div><div class="stat-label">Avg confidence</div></div>
    <div class="stat"><div class="stat-val">${records.length}</div><div class="stat-label">Predictions</div></div>
  </div>
  <h2>Prediction History</h2>
  <table><thead><tr><th>Date</th><th>Action</th><th>Confidence</th><th>Mode</th><th>Savings</th><th>Solar</th><th>Stage</th><th>SOC</th></tr></thead><tbody>`

  records.forEach(r => {
    html += `<tr>
      <td>${new Date(r.createdAt).toLocaleString('en-ZA')}</td>
      <td>${r.action}</td>
      <td>${(r.confidence * 100).toFixed(0)}%</td>
      <td>${r.operatingMode}</td>
      <td>R${r.estimatedSavingsRand.toFixed(2)}</td>
      <td>${r.solarForecastKwh.toFixed(1)} kWh</td>
      <td>${r.loadSheddingStage}</td>
      <td>${r.currentSoc.toFixed(1)}%</td>
    </tr>`
  })

  html += `</tbody></table>
  <p style="margin-top:24px;font-size:11px;color:#999">Report generated by OptiGrid ZA · ${date}</p>
  </body></html>`

  const w = window.open('', '_blank')
  w.document.write(html)
  w.document.close()
  w.print()
}

const actionColor = { CHARGE: '#1E7A6B', DISCHARGE: '#C0341B', HOLD: '#F2610C', SOLAR_PRIORITY: '#EAB308' }

export default function History() {
  const { user } = useAuth()
  const [records, setRecords] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    if (!user?.companyId) return
    apiFetch(`/api/v1/prediction/history/${user.companyId}`)
      .then(data => { setRecords(data); setError('') })
      .catch(() => setError('Could not load prediction history.'))
      .finally(() => setLoading(false))
  }, [user])

  const totalSavings = records.reduce((s, r) => s + r.estimatedSavingsRand, 0)
  const avgConfidence = records.length ? records.reduce((s, r) => s + r.confidence, 0) / records.length : 0

  const sorted = [...records].sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt))

  const chartData = {
    labels: sorted.map(r => new Date(r.createdAt).toLocaleDateString('en-ZA', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })),
    datasets: [
      {
        label: 'Savings (R)',
        data: sorted.map(r => r.estimatedSavingsRand),
        borderColor: '#1E7A6B',
        backgroundColor: 'rgba(30,122,107,0.1)',
        fill: true,
        tension: 0.3,
        yAxisID: 'y',
      },
      {
        label: 'SOC (%)',
        data: sorted.map(r => r.currentSoc),
        borderColor: '#F2610C',
        backgroundColor: 'rgba(242,97,12,0.1)',
        fill: false,
        tension: 0.3,
        yAxisID: 'y1',
      },
    ],
  }

  const chartOptions = {
    maintainAspectRatio: false,
    interaction: { mode: 'index', intersect: false },
    plugins: { legend: { position: 'top' } },
    scales: {
      y: { type: 'linear', position: 'left', title: { display: true, text: 'Savings (R)' } },
      y1: { type: 'linear', position: 'right', min: 0, max: 100, title: { display: true, text: 'SOC (%)' }, grid: { drawOnChartArea: false } },
    },
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="font-display text-2xl font-bold">Prediction History</h1>
          <p className="text-sm text-base-content/60">Historical AI recommendations and performance</p>
        </div>
        <div className="flex gap-2">
          <button className="btn btn-sm btn-outline" onClick={() => downloadCSV(records)} disabled={records.length === 0}>
            📥 CSV
          </button>
          <button className="btn btn-sm btn-primary" onClick={() => downloadPDF(records)} disabled={records.length === 0}>
            📄 PDF Report
          </button>
        </div>
      </div>

      {error && <div className="alert alert-error mb-6">{error}</div>}

      {/* Summary stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <div className="stat bg-base-100 rounded-box shadow border border-base-300">
          <div className="stat-title">Total Predictions</div>
          <div className="stat-value text-primary">{records.length}</div>
        </div>
        <div className="stat bg-base-100 rounded-box shadow border border-base-300">
          <div className="stat-title">Total Savings</div>
          <div className="stat-value text-success">R{totalSavings.toFixed(2)}</div>
        </div>
        <div className="stat bg-base-100 rounded-box shadow border border-base-300">
          <div className="stat-title">Avg Confidence</div>
          <div className="stat-value">{(avgConfidence * 100).toFixed(0)}%</div>
        </div>
        <div className="stat bg-base-100 rounded-box shadow border border-base-300">
          <div className="stat-title">Latest Action</div>
          <div className="stat-value text-lg">{records.length ? records[0].action : '—'}</div>
        </div>
      </div>

      {/* Chart */}
      {sorted.length > 1 && (
        <div className="card bg-base-100 shadow border border-base-300 mb-6">
          <div className="card-body">
            <h2 className="card-title font-display">Savings & SOC Trend</h2>
            <div className="h-64">
              <Line data={chartData} options={chartOptions} />
            </div>
          </div>
        </div>
      )}

      {/* Table */}
      {loading ? (
        <div className="flex justify-center py-12"><span className="loading loading-spinner loading-lg"></span></div>
      ) : records.length === 0 ? (
        <div className="card bg-base-100 shadow border border-base-300">
          <div className="card-body items-center py-12">
            <span className="text-4xl mb-2">📊</span>
            <p className="text-base-content/60">No prediction history yet — predictions are saved each time the dashboard loads.</p>
          </div>
        </div>
      ) : (
        <div className="card bg-base-100 shadow border border-base-300">
          <div className="card-body overflow-x-auto">
            <h2 className="card-title font-display">All Predictions</h2>
            <table className="table table-sm">
              <thead>
                <tr>
                  <th>Date</th>
                  <th>Action</th>
                  <th>Confidence</th>
                  <th>Mode</th>
                  <th>Savings</th>
                  <th>Solar</th>
                  <th>Stage</th>
                  <th>SOC</th>
                  <th>Reasoning</th>
                </tr>
              </thead>
              <tbody>
                {records.map(r => (
                  <tr key={r.id}>
                    <td className="whitespace-nowrap text-xs">{new Date(r.createdAt).toLocaleString('en-ZA')}</td>
                    <td>
                      <span className="badge badge-sm" style={{ backgroundColor: actionColor[r.action] || '#888', color: '#fff' }}>
                        {r.action}
                      </span>
                    </td>
                    <td>{(r.confidence * 100).toFixed(0)}%</td>
                    <td className="text-xs">{r.operatingMode}</td>
                    <td className="text-success font-medium">R{r.estimatedSavingsRand.toFixed(2)}</td>
                    <td>{r.solarForecastKwh.toFixed(1)}</td>
                    <td>{r.loadSheddingStage}</td>
                    <td>{r.currentSoc.toFixed(1)}%</td>
                    <td className="text-xs max-w-xs truncate" title={r.reasoning}>{r.reasoning}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  )
}
