server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: true
          discovery:
            locator:
              enabled: false
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/api/v1/companies/**

            - id: etl-service
              uri: lb://etl-service
              predicates:
                - Path=/api/v1/etl/**

            - id: prediction-service
              uri: lb://prediction-service
              predicates:
                - Path=/api/v1/prediction/**

            - id: simulation-service
              uri: lb://simulation-service
              predicates:
                - Path=/api/v1/simulation/**

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/v1/notifications/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true