server:
  port: 8084

spring:
  application:
    name: prediction-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/optigridza_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin@123}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: prediction

jwt:
  secret: ${JWT_SECRET:R0UD3CdgthTnzfxxoZsnhTjredMwKfaunCF2K8qcCdU}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring.cloud.openfeign.circuitbreaker:
  enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10s
      permitted-number-of-calls-in-half-open-state: 3

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: when-authorized

prediction:
  retention:
    days: ${PREDICTION_RETENTION_DAYS:90}
