server:
  port: 8083

spring:
  application:
    name: etl-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/optigridza_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin@123}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: etl

jwt:
  secret: ${JWT_SECRET:R0UD3CdgthTnzfxxoZsnhTjredMwKfaunCF2K8qcCdU}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

api:
  openmeteo:
    base-url: https://api.open-meteo.com/v1/forecast
  eskomsepush:
    key: ${ESKOM_API_KEY:A129B4CD-069D4E92-9E4DE31D-09C7934A}
    base-url: https://developer.sepush.co.za/business/2.0
  location:
    city: Pretoria
    lat: -25.7463
    lon: 28.1876

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

